name: enrich places-basrow with coordinates
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  download:
    name: enrich places-basrow with coordinates
    runs-on: ubuntu-latest
    env:
      GITHUB_USER_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: fetch lemmas in context
        run: |
          curl --request GET \
          --url 'https://raw.githubusercontent.com/NestroyCA/working-data/main/json/cleaned_lemma_context.json' \
          --header "authorization: token $GITHUB_USER_TOKEN" \
          -H 'Accept: application/vnd.github.v3.raw' \
          -o ./json_dumps/lemma_context.json
      - name: dump the data
        run: |
          python dump_data.py
      - name: enrich with coordinates
        run: |
          python enrich_baserow_data.py
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updated from Baserow