name: Dump Entities from Baserow

on:
  workflow_dispatch:

jobs:
  download:
    name: enrich places-basrow with coordinates
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: dump the data
        run: |
          python dump_data.py
      - name: enrich with coordinates
        run: |
          python create_koordinates.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updated from Baserow & added coordinates to baserow
