name: enrich places-basrow with coordinates
on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
  push:

jobs:
  download:
    name: enrich places-basrow with coordinates
    runs-on: ubuntu-latest
    env:
      GITHUB_USER_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
      BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
      BASEROW_USER: ${{ secrets.BASEROW_USER }}
      BASEROW_PW: ${{ secrets.BASEROW_PW }}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: fetch lemmas in context
        run: |
          ./fetch_lemmas.sh $GITHUB_USER_TOKEN
      - name: dump the data
        run: |
          python dump_data.py
      - name: enrich with coordinates
        run: |
          python enrich_baserow_data.py
      - name: Commit new data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updated from Baserow